service: online-railway-reservation

provider: 
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 15
  stage: production
  region: us-west-1

functions: 
  bookingApi:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /